version: '2'
services:
  db:
    container_name: nekobot_mongodb
    image: mongo:latest
    volumes:
      - data:/data/db

  dbweb:
    container_name: nekobot_dbweb
    image: mongo-express:latest
    ports:
      - "8081:8081"
    depends_on:
      - db
    links:
      - db:mongo
    env_file:
      - ./nekobot.rc

  nekobot:
    container_name: nekobot_discord
    build: ./bot
    links:
      - db:mongodb
    env_file:
      - ./nekobot.rc

  nginx:
    container_name: nekobot_nginx
    build: ./nginx
    depends_on:
      - web
    links:
      - web
    ports:
      - "80:80"
      - "443:443"

  web:
    container_name: nekobot_web
    build: ./web
    env_file:
      - ./nekobot.rc

volumes:
  data:

