version: '2'
services:
  db:
    restart: always
    container_name: nekobot_mongodb
    image: mongo:latest
    volumes:
      - /mnt/data/mongodb:/data/db
#      - data/mongodb:/data/db

  nekobot:
    restart: always
    container_name: nekobot_discord
    build: ./bot
    links:
      - db:mongodb
    env_file:
      - ./nekobot.rc

  nginx:
    restart: always
    container_name: nekobot_nginx
    build: ./nginx
    depends_on:
      - web
    links:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /mnt/data/nginx/certs:/etc/letsencrypt/live/nekobot.xyz
      - /mnt/data/nginx/logs:/var/log/nginx
      - /mnt/data/letsencrypt/logs:/var/log/letsencrypt
      - /mnt/data/letsencrypt/conf:/etc/letsencrypt
      - /mnt/data/nginx/certs:/certs

  web:
    restart: always
    container_name: nekobot_web
    build: ./web
    env_file:
      - ./nekobot.rc

volumes:
  data:

