version: '2'
services:
  db:
    container_name: nekobot_mongodb

    image: mongo:latest

    volumes:
      - data:/data/db

  nekobot:
    container_name: nekobot_discord

    build: ./bot

    links:
      - db:mongodb

    env_file:
      - ./nekobot.rc

volumes:
  data:

